[tool.poetry]
name = "students-ui"
version = "0.1.0"
description = ""
authors = ["uehrlich <uriehrlich@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
conan = "^2.0.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
